### ISSUE TITLE
Conflict with empty branches

### ISSUE THREAD

**Issue by danielo515** [gitbutlerapp/gitbutler-docs#15]
Hello.
I was just testing the most basic feature (having a virtual branch and just push changes to it), and at some point, after pushing, I got an error like this:
![Screenshot 2024-07-19 at 14 45 30](https://github.com/user-attachments/assets/36a7a577-6b40-4b86-9a68-9d406f350125)

As you can see, there is not branches referenced (which I assume they should) and as a result, I am now in some kind of limbo. My project as a weird branch stashed and I don't know how to fix those conflicts that do not appear anywhere.

**Comment by ndom91** [comment]
Hey @danielo515 this is the wrong place for support for the product unfortunately. Can you recreate this under "https://github.com/gitbutlerapp/gitbutler/issues" instead? Thanks!
