### ISSUE TITLE
No mention of brief_style or emoji_style in docs, or other template tokens available

### ISSUE THREAD

**Issue by bdmorin** [gitbutlerapp/gitbutler-docs#18]
### What is the improvement or update you wish to see?

I wanted to modify the AI commit messages, and there are 2 lines in the default.
%{brief_style}
%{emoji_style}

I don't know what they do, how to configure them, or if I need them.

### Is there any context that might help us understand?

I think the default message is great, however I need to ask GB to incorporate Linear.com ticket mentions in commit messages. I don't now how I want to do it yet, but if there are some kind of templating/tokens I can make use of I'd like to try to do that. 

### Does the docs page already exist? Please link to it.

I couldn't find it if it was.

**Comment by ndom91** [comment]
Hey thanks for bringing this to our attention! I've added some mention of them to the docs [here](https://github.com/gitbutlerapp/gitbutler-docs/pull/19)

**Comment by bdmorin** [comment]
Thanks!
