### ISSUE TITLE
Feedback for page "features/virtual-branches/overview"

### ISSUE THREAD

**Issue by exalted** [gitbutlerapp/gitbutler-docs#36]
Hey there! I L-O-V-E what you're doing here.

I just wanted to stop by to say that I would 2x ❤️ if GitButler could work seamlessly "on top of" a regular git client where you could be checked out on any git branch, at any given time.

Although I somewhat understand the technical reasons why this is true, I wish it wasn't the case:

> You cannot use both GitButler virtual branches and normal Git branching commands at the same time, you will have to "commit" to one approach or the other.

I am not yet willing to fully commit to GitButler flow, however, I'd like to use GitButler to supercharge my git-flow [with virtual branches] to "separate" somewhat unrelated work from the "main work" I am doing on a git feature branch (e.g., fixing a bug, doing some type of refactoring, etc.) then to separately merge that unrelated work into "main" without having to do the stash/temp-commit, branch-switching, etc. dance.

**Comment by ndom91** [comment]
Hey @exalted thanks a lot for reaching out and the positive feedback :blush: 

While it's currently not quite possible to work as you're envisioning above, we do plan to make interoperability with the normal git cli better and better

That being said, GitButler is great at exactly the sort of workflow you're describing - no need to go back and forth between it and using the CLI. 

I often have 1 longer lasting branch that is the main piece of work I'm working on for the day / week, and then when smaller requests come in or little fixes need to be made its super simple to make another branch and put those changes in it only. Push that branch and simultaenously keep working on your primary piece of work branch. If you're curious to give it a go, we've recently released a "Getting Started" [guide](https://docs.gitbutler.com/guide) that should help you get up and running quicker :wink:

**Comment by exalted** [comment]
Thanks, @ndom91. It's just that I am not willing to let my years of accumulated CLI workflow go, not yet. Keep up the great work. ✌️
